/**
 * Pikalytics-sourced team cores — 2-, 3-, and 4-mon partner groupings that
 * appear most often on top Champions VGC tournament teams. Generated by the
 * Pikalytics scraper; no UI consumer wired yet. Reserved for a future
 * "common partners" surface on Suggestions / team builder.
 */
export { PIKALYTICS_CORES as TEAM_CORES, type PikalyticsCore as TeamCore } from '@/data/generated/pikalytics-cores.generated';
