import { PIKALYTICS_PRESET_TEAMS } from '@/data/generated/pikalytics-presets.generated';
import type { SavedMon } from '@/types';

/**
 * Real tournament-winning Champions VGC teams that show up in the Teams
 * screen's empty state, generated from Pikalytics's top tournament finishers.
 * Auto-regenerated by `npm run scrape:pikalytics`. Each team's per-mon item /
 * ability / moveset comes straight from the player's submitted sheet; the
 * nature/SPs are filled from that species's modal Pikalytics spread (top sheet
 * shape) because tournament submissions don't include EV/IV detail.
 *
 * If Pikalytics's data ever degrades or the doubles slice goes empty, fall
 * back to the prior hand-curated lists by reverting this file.
 */
export interface PresetTeam {
  name: string;
  /** One-line vibe so the user knows what they're picking. */
  blurb: string;
  format: 'singles' | 'doubles';
  /** Mons without `id` — TeamsScreen stamps fresh uuids on apply. */
  mons: Omit<SavedMon, 'id'>[];
}

export const PRESET_TEAMS: PresetTeam[] = PIKALYTICS_PRESET_TEAMS.map((t) => ({
  name: t.name,
  blurb: t.blurb,
  format: 'doubles',
  mons: t.mons,
}));
